name: PMPluginManager
main: HittmanA\PMPluginManager\MainClass
version: 2.0.5
api: 3.0.0-ALPHA6
description: Official PMPM plugin
commands:
  download:
    description: Downloads the specified plugin from the poggit registry.
    usage: /download <plugin>
    aliases: [add, addplugin, getplugin, dl]
  remove:
    description: Removes the specified plugin from your server
    usage: /remove <plugin>
    aliases: [rm, delete]
  __UpdateSelf:
    description: Update the PMPM plugin
    usage: /__UpdateSelf
    